# Generated by Django 4.0.1 on 2022-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique_for_date='publish'),
        ),
    ]
